services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes: 
      - mongo-data:/data/db
  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/chat_app_db
    depends_on:
      - mongo
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
volumes:
  mongo-data:
