services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes: 
      - mongo-data:/data/db

  # multiple backend instances to test nginx load balance
  server-1:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/chat_app_db
    depends_on:
      - mongo

  server-2:
    build: ./server
    ports:
      - "5001:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/chat_app_db
    depends_on:
      - mongo

  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - server-1
      - server-2
    restart: unless-stopped

volumes:
  mongo-data:
